/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SFaqBlockSection, } from "./components/s-cnt-faq-block-section/interface/common.interface";
import { SFaqBlocks, } from "./components/s-cnt-faq-block-section/res/view/s-cnt-faq-blocks/interface/common.interface";
import { SFaqElements, } from "./components/s-cnt-faq-search/interface/common.interface";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SCntFaqBlockSection {
        /**
          * Получение данных из массива для вывода
         */
        "blockSection": SFaqBlockSection[];
    }
    interface SCntFaqBlocks {
        /**
          * Получение данных из массива для вывода
         */
        "blocks": SFaqBlocks[];
    }
    interface SCntFaqSearch {
        /**
          * Прием данных из массива
         */
        "header": SFaqElements[];
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSCntFaqBlockSectionElement extends Components.SCntFaqBlockSection, HTMLStencilElement {
    }
    var HTMLSCntFaqBlockSectionElement: {
        prototype: HTMLSCntFaqBlockSectionElement;
        new (): HTMLSCntFaqBlockSectionElement;
    };
    interface HTMLSCntFaqBlocksElement extends Components.SCntFaqBlocks, HTMLStencilElement {
    }
    var HTMLSCntFaqBlocksElement: {
        prototype: HTMLSCntFaqBlocksElement;
        new (): HTMLSCntFaqBlocksElement;
    };
    interface HTMLSCntFaqSearchElement extends Components.SCntFaqSearch, HTMLStencilElement {
    }
    var HTMLSCntFaqSearchElement: {
        prototype: HTMLSCntFaqSearchElement;
        new (): HTMLSCntFaqSearchElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "s-cnt-faq-block-section": HTMLSCntFaqBlockSectionElement;
        "s-cnt-faq-blocks": HTMLSCntFaqBlocksElement;
        "s-cnt-faq-search": HTMLSCntFaqSearchElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SCntFaqBlockSection {
        /**
          * Получение данных из массива для вывода
         */
        "blockSection"?: SFaqBlockSection[];
        /**
          * Клик по блоку автора компонента 'blocks'
         */
        "onClickBlockAuthor"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Заголовку компонента 'blocks'
         */
        "onClickBlockHeader"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по картинке компонента 'blocks'
         */
        "onClickBlockImg"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту компонента 'blocks'
         */
        "onClickBlockText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по кнопке на страницу вперед
         */
        "onClickLeft"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по ссылке
         */
        "onClickLink"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по кнопке на страницу назад
         */
        "onClickRight"?: (event: CustomEvent<any>) => void;
    }
    interface SCntFaqBlocks {
        /**
          * Получение данных из массива для вывода
         */
        "blocks"?: SFaqBlocks[];
        /**
          * Клик по блоку автора
         */
        "onClickBlockAuthor"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Заголовку
         */
        "onClickBlockHeader"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по картинке
         */
        "onClickBlockImg"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickBlockText"?: (event: CustomEvent<any>) => void;
    }
    interface SCntFaqSearch {
        /**
          * Прием данных из массива
         */
        "header"?: SFaqElements[];
        /**
          * Клик по кнопке назад
         */
        "onClickBack"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по категориям
         */
        "onClickCategory"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Логотипу
         */
        "onClickLogo"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по  ссылкам меню
         */
        "onClickMenu"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по кнопке поиска
         */
        "onClickSearch"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "s-cnt-faq-block-section": SCntFaqBlockSection;
        "s-cnt-faq-blocks": SCntFaqBlocks;
        "s-cnt-faq-search": SCntFaqSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "s-cnt-faq-block-section": LocalJSX.SCntFaqBlockSection & JSXBase.HTMLAttributes<HTMLSCntFaqBlockSectionElement>;
            "s-cnt-faq-blocks": LocalJSX.SCntFaqBlocks & JSXBase.HTMLAttributes<HTMLSCntFaqBlocksElement>;
            "s-cnt-faq-search": LocalJSX.SCntFaqSearch & JSXBase.HTMLAttributes<HTMLSCntFaqSearchElement>;
        }
    }
}
